version: "3.9"

services:
  redis:
    image: redis
    command: ["redis-server",  "--requirepass", "password"]
    ports:
      - "6379:6379"
  login:
    container_name: login
    restart: on-failure
    build: .
    env_file:
      - ./.env
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - "./:/login"
    depends_on:
      - redis
